### ISSUE TITLE
Bots not picking

### ISSUE THREAD

**Issue by v3rlain3** [arzon4dt/bot-experiment#2]
Bots not picking with the latest changes on hero_selection.lua, i modify the values of maxPlayerID but still the same; bots not picking, i got back to the previous version. regards

**Comment by v3rlain3** [comment]
Not picking in ap mode, cm mode work fine.
Regards

**Comment by lrvd00** [comment]
Works fine to me. Have u tried to type heroes' names on the chat?
Regards

**Comment by v3rlain3** [comment]
Solved; was the dota version, after updating everything ok/
