### ISSUE TITLE
Give orders to bots

### ISSUE THREAD

**Issue by icamys** [arzon4dt/bot-experiment#3]
Is there any way to add ability of giving orders to bots?

For example:

`-aid` - give human some healing items
`-back` - retreat to the nearest tower
`-defend-top` - defend last top tower
`-focus-1` - focus attack on first player in enemy team
`-do-farm` - keep farming one minute
`-dismissed` - back to usual behaviour
etc.

**Comment by arzon4dt** [comment]
Here are the references :
[https://developer.valvesoftware.com/wiki/Dota_Bot_Scripting](url)
[http://docs.moddota.com/lua_bots/](url)
And if you want to integrate that commands with human chat (only human chat) to change the current bot mode you can take a look at this post on how to make the bot recognize a human chat
[https://dev.dota2.com/showthread.php?t=276990&p=1437197&viewfull=1#post1437197](url)

**Comment by icamys** [comment]
@arzon4dt Thank you for your response and for the links! It helped me very much.
I've fixed an annoying bug using this guides. Please check my PR #6.
