### ISSUE TITLE
How to change laning behaviour?

### ISSUE THREAD

**Issue by icamys** [arzon4dt/bot-experiment#4]
I would like to enhance bots behaviour on laning phase. Could you please elaborate how to make this?

**Comment by arzon4dt** [comment]
You can take a look at this reference [https://developer.valvesoftware.com/wiki/Dota_Bot_Scripting](url)
on how to override current bot mode. If you want some examples you can take a look at my **mode_rune_generic.lua (for overriding rune mode on bot)** or **mode_ward_generic.lua (for overriding warding mode on bot)** file.

**Comment by icamys** [comment]
@arzon4dt Thanks for advice!
